import type { Metadata } from 'next';
import {
  BarChart3,
  Brain,
  Bus,
  Camera,
  CheckCircle,
  Cpu,
  Clock3,
  Eye,
  HardHat,
  Layers3,
  MapPin,
  Recycle,
  RotateCcw,
  ScanEye,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Siren,
  Truck,
  Users,
  Wifi,
  Zap,
} from 'lucide-react';

import type { SolutionPageData } from '@/components/sections/solution-page';

type SolutionPageEntry = {
  metadata: Metadata;
  page: SolutionPageData;
};

const sharedRelatedLinks = {
  autobuses: { href: '/adas-autobuses', label: 'ADAS para Autobuses' },
  camiones: { href: '/adas-camiones', label: 'ADAS para Camiones' },
  antiAtropellos: { href: '/anti-atropellos-peatones-ciclistas', label: 'Sistema Anti-Atropellos' },
  camaras: { href: '/camaras-vision-artificial-flotas', label: 'Cámaras con Visión Artificial' },
  vision360: { href: '/vision-360-vehiculos-industriales', label: 'Visión 360° Vehículos Industriales' },
  residuos: { href: '/adas-vehiculos-recogida-residuos', label: 'ADAS Recogida de Residuos' },
  bsis: { href: '/bsis-camiones-autobuses', label: 'Sistema BSIS para Camiones y Autobuses' },
  fcw: { href: '/fcw-flotas', label: 'Sistema FCW para Flotas' },
  autocares: { href: '/adas-autocares-minibuses', label: 'ADAS para Autocares y Minibuses' },
  furgonetas: { href: '/adas-furgonetas-reparto', label: 'ADAS para Furgonetas de Reparto' },
  aeropuerto: { href: '/adas-aeropuerto-lanzaderas', label: 'ADAS para Aeropuerto y Lanzaderas' },
  portuaria: { href: '/adas-logistica-portuaria', label: 'ADAS para Logística Portuaria' },
  construccion: { href: '/adas-construccion-obra', label: 'ADAS para Construcción y Obra' },
};

export const solutionPages: Record<string, SolutionPageEntry> = {
  'adas-autobuses': {
    metadata: {
      title: 'ADAS para autobuses con cámaras 360° y detección VRU | Vision360IA',
      description: 'Reduce puntos ciegos y accidentes en autobuses urbanos e interurbanos con cámaras 360°, detección de peatones y ciclistas y solución preparada para cumplimiento GSR en flotas profesionales.',
      keywords: ['ADAS autobuses', 'ADAS autobuses urbanos', 'visión 360 autobuses', 'anti atropellos autobuses', 'cámaras visión artificial autobuses', 'GSR autobuses', 'puntos ciegos autobuses'],
      openGraph: {
        title: 'Seguridad 360° para flotas de autobuses | Vision360IA',
        description: 'Solución ADAS para autobuses que reduce puntos ciegos, protege a peatones y ciclistas y facilita operación segura en entornos urbanos complejos.',
      },
      alternates: {
        canonical: 'https://www.vision360ia.com/adas-autobuses',
      },
    },
    page: {
      breadcrumbLabel: 'ADAS para Autobuses',
      schemas: [
        {
          '@context': 'https://schema.org',
          '@type': 'FAQPage',
          mainEntity: [
            {
              '@type': 'Question',
              name: '¿Qué sistema ADAS ayuda a reducir puntos ciegos en autobuses urbanos?',
              acceptedAnswer: {
                '@type': 'Answer',
                text: 'Vision360IA combina cámaras 360°, detección de peatones y ciclistas con IA y arquitectura preparada para operación urbana intensiva. Ayuda a reducir puntos ciegos en giros, arranques y maniobras de parada, y facilita cumplimiento GSR en flotas profesionales.',
              },
            },
            {
              '@type': 'Question',
              name: '¿Cómo se amortiza un sistema ADAS en una flota de autobuses?',
              acceptedAnswer: {
                '@type': 'Answer',
                text: 'Normalmente se amortiza evitando uno o dos incidentes relevantes, reduciendo inmovilizaciones, reclamaciones y exposición al riesgo en maniobras urbanas. La configuración depende de la geometría del vehículo y del nivel de integración requerido por la flota.',
              },
            },
            {
              '@type': 'Question',
              name: '¿El sistema ADAS para autobuses facilita cumplimiento GSR europeo?',
              acceptedAnswer: {
                '@type': 'Answer',
                text: 'Sí. Vision360IA está preparado para R151, R158 y R159, lo que ayuda a operadores y talleres a desplegar una solución coherente en retrofit sobre autobuses de servicio urbano e interurbano ya operativos.',
              },
            },
            {
              '@type': 'Question',
              name: '¿Cómo se implanta el sistema en una flota de autobuses ya operativa?',
              acceptedAnswer: {
                '@type': 'Answer',
                text: 'Se estudia la geometría del vehículo y sus maniobras críticas, se diseña la cobertura de cámaras, se instala y calibra la solución y se valida en servicio antes de escalar el despliegue al resto de la flota.',
              },
            },
          ],
        },
        {
          '@context': 'https://schema.org',
          '@type': 'Product',
          name: 'Sistema ADAS para Autobuses - Vision360IA',
          description: 'Sistema ADAS para autobuses con cámaras 360°, detección de peatones y ciclistas y arquitectura preparada para mejorar seguridad urbana y facilitar cumplimiento GSR en flotas profesionales.',
          brand: { '@type': 'Brand', name: 'Vision360IA' },
          category: 'Sistemas ADAS para Autobuses',
          offers: {
            '@type': 'Offer',
            availability: 'https://schema.org/InStock',
            priceCurrency: 'EUR',
          },
        },
      ],
      theme: {
        heroBackground: 'min-h-screen bg-[radial-gradient(circle_at_top,rgba(56,189,248,0.16),transparent_24%),linear-gradient(180deg,#0f172a_0%,#111827_20%,#f8fafc_56%,#ffffff_100%)]',
        heroGlowPrimary: 'bg-sky-400/16',
        heroGlowSecondary: 'bg-amber-300/12',
        heroAccentText: 'text-sky-300',
        heroPanelIconBg: 'bg-sky-500/20',
        heroPanelIconText: 'text-sky-300',
        heroGainText: 'text-sky-300',
        primaryButton: 'bg-sky-500 text-white shadow-[0_20px_45px_rgba(59,130,246,0.28)] hover:bg-sky-600',
        eyebrowText: 'text-sky-700/80',
        metricBackground: 'bg-[radial-gradient(circle_at_top,rgba(56,189,248,0.14),transparent_28%),linear-gradient(180deg,#0f172a,#111827)]',
        metricEyebrowText: 'text-sky-300/80',
        ctaBackground: 'bg-[radial-gradient(circle_at_top,rgba(56,189,248,0.2),transparent_28%),linear-gradient(180deg,#0f172a,#020617)]',
        ctaEyebrowText: 'text-sky-300/80',
        detailBullet: 'bg-sky-500',
      },
      hero: {
        badge: 'ADAS para flotas de autobuses',
        badgeIcon: Bus,
        title: 'Reduce puntos ciegos y maniobras de riesgo en tu flota de autobuses',
        description: 'Sistema de cámaras 360° con detección inteligente de peatones y ciclistas para autobuses urbanos e interurbanos. Diseñado para mejorar seguridad, reducir incidentes y facilitar cumplimiento sin penalizar la operación.',
        highlights: ['Paradas frecuentes en entorno urbano', 'Exposición continua a peatones y ciclistas', 'Giros con ángulo muerto crítico', 'Operación intensiva con presión de servicio'],
        primaryCtaLabel: 'Solicitar información técnica',
        secondaryCtaLabel: 'Ver demostración en vídeo',
        panelEyebrow: 'Entorno de operación',
        panelTitle: 'Operación urbana con exposición constante al riesgo',
        panelIcon: Users,
        stats: [
          { value: '+2.000', label: 'vehículos instalados' },
          { value: '40%', label: 'menos incidentes en maniobra' },
          { value: 'GSR', label: 'R151, R158 y R159' },
        ],
        gains: [
          'Menos exposición a incidentes en giros, paradas y arranques.',
          'Mayor visibilidad para el conductor en servicio urbano intensivo.',
          'Despliegue compatible con operación real y retrofit sobre flota existente.',
        ],
      },
      context: {
        eyebrow: 'Riesgo operativo',
        title: 'El mayor riesgo en autobuses urbanos: los puntos ciegos',
        paragraphs: [
          'Un autobús opera todos los días en entornos con peatones, ciclistas, scooters, tráfico denso y paradas continuas. Esa combinación multiplica el riesgo en maniobras de baja velocidad y en giros con visibilidad limitada.',
          'Vision360IA elimina esos puntos ciegos con visión cenital 360° y detección inteligente de usuarios vulnerables de la vía en las zonas de mayor exposición.',
          'No es solo una cámara: es una solución activa para ayudar al conductor a reaccionar antes de que una maniobra termine en incidente, reclamación o parada de servicio.',
        ],
        asideEyebrow: 'Escenarios críticos',
        asideItems: ['Giros urbanos con ángulo muerto lateral.', 'Arranque en parada con cruce de pasajeros.', 'Intercambios con bicicletas y VMP.', 'Operación continua en tráfico denso y horarios extensos.'],
      },
      implementation: {
        eyebrow: 'Implantación en flota real',
        title: 'Cómo se despliega en autobuses sin improvisar la instalación',
        description: 'En autobuses urbanos e interurbanos no basta con instalar cámaras. Hay que estudiar geometría, zonas de cobertura, hábitos de maniobra y entorno operativo para que la solución ayude de verdad al conductor y a la operación.',
        steps: [
          'Estudio previo de tipología, longitud y zonas críticas del autobús.',
          'Diseño de cobertura para giro, parada, arranque y maniobra urbana.',
          'Instalación y calibración sobre flota existente en operación.',
          'Validación en servicio antes de escalar el despliegue al resto de la flota.',
        ],
      },
      features: {
        eyebrow: 'Arquitectura para flota',
        title: 'Beneficios para operadores de autobús y gestores de flota',
        cards: [
          {
            icon: Eye,
            title: 'Elimina puntos ciegos en maniobras urbanas',
            desc: 'Cámaras HD con vista cenital unificada para mejorar visibilidad en giros, salidas de parada y maniobras en calles estrechas.',
            tone: 'border-sky-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(239,246,255,0.96))]',
            iconTone: 'bg-gradient-to-br from-sky-500 to-blue-600',
            tag: 'Prevención visual',
          },
          {
            icon: ShieldCheck,
            title: 'Protege a peatones y ciclistas en tiempo real',
            desc: 'La IA detecta usuarios vulnerables de la vía en zonas de riesgo y alerta al conductor antes de que la maniobra termine en incidente.',
            tone: 'border-amber-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(255,251,235,0.96))]',
            iconTone: 'bg-gradient-to-br from-amber-400 to-orange-500',
            tag: 'Protección VRU',
          },
          {
            icon: Brain,
            title: 'Analiza el riesgo antes de que llegue el siniestro',
            desc: 'Algoritmos embarcados procesan el entorno en milisegundos para clasificar riesgos y mejorar la reacción del conductor.',
            tone: 'border-emerald-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(236,253,245,0.96))]',
            iconTone: 'bg-gradient-to-br from-emerald-500 to-teal-500',
            tag: 'IA embarcada',
          },
          {
            icon: CheckCircle,
            title: 'Facilita cumplimiento GSR en flota real',
            desc: 'Arquitectura preparada para R151, R158 y R159 en retrofit sobre autobuses ya operativos.',
            tone: 'border-violet-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(245,243,255,0.96))]',
            iconTone: 'bg-gradient-to-br from-violet-500 to-fuchsia-500',
            tag: 'Normativa',
          },
        ],
      },
      detailSection: {
        eyebrow: 'Tipos de flota',
        title: 'Configuración adaptable a distintas tipologías de servicio',
        description: 'Una misma arquitectura puede adaptarse a urbano, interurbano, lanzaderas o retrofit según geometría del vehículo y nivel de exposición al riesgo.',
        variant: 'chips',
        items: ['Urbanos', 'Interurbanos', 'Lanzaderas', 'BRT', 'Escolares', 'Regionales', 'Aeropuerto', 'Retrofit'],
      },
      metrics: {
        eyebrow: 'Resultados reales',
        title: 'Impacto directo en seguridad y operación',
        items: [
          { value: '360°', label: 'cobertura perimetral' },
          { value: 'IP69K', label: 'grado industrial' },
          { value: '< 1 min', label: 'calibración automática' },
          { value: '24/7', label: 'operación de flota' },
        ],
      },
      faq: {
        eyebrow: 'FAQ para operadores',
        title: 'Preguntas frecuentes sobre seguridad 360° en autobuses',
        items: [
          {
            question: '¿Qué sistema ayuda a reducir puntos ciegos en autobuses urbanos?',
            answer: 'Una solución que combine visión cenital 360°, detección de peatones y ciclistas y arquitectura pensada para servicio urbano real. Vision360IA está diseñada precisamente para ese escenario.',
          },
          {
            question: '¿Cómo se amortiza un sistema ADAS en una flota de autobuses?',
            answer: 'Normalmente evitando uno o dos incidentes relevantes, reduciendo inmovilizaciones, reclamaciones y exposición al riesgo en maniobras de parada y giro.',
          },
          {
            question: '¿La solución facilita cumplimiento GSR?',
            answer: 'Sí. Vision360IA está preparada para R151, R158 y R159, lo que facilita despliegues coherentes en retrofit sobre flota existente.',
          },
          {
            question: '¿Cómo se instala y valida en una flota de autobuses en servicio?',
            answer: 'La instalación parte de un análisis del vehículo y de sus maniobras críticas. Después se define la cobertura, se calibra el sistema y se valida en operación antes de ampliar el despliegue al resto de la flota.',
          },
        ],
      },
      cta: {
        eyebrow: 'Siguiente paso',
        title: 'Protege tu flota de autobuses con visión 360° inteligente',
        description: 'Solicita una sesión técnica para revisar riesgos, tipología de servicio y la configuración más eficaz para tu operación.',
        primaryCtaLabel: 'Ver si encaja en mi flota',
        relatedLinks: [sharedRelatedLinks.autocares, sharedRelatedLinks.aeropuerto, sharedRelatedLinks.antiAtropellos, sharedRelatedLinks.bsis, sharedRelatedLinks.fcw],
      },
    },
  },
  'adas-camiones': {
    metadata: {
      title: 'ADAS para camiones con cámaras 360° y alertas VRU | Vision360IA',
      description: 'Reduce puntos ciegos y riesgo de siniestro en camiones y transporte pesado con cámaras 360°, detección de peatones y ciclistas y solución preparada para retrofit y cumplimiento GSR.',
      keywords: ['ADAS camiones', 'ADAS transporte pesado', 'visión 360 camiones', 'cámaras visión artificial camiones', 'anti atropellos camiones', 'puntos ciegos camiones', 'GSR camiones'],
      openGraph: {
        title: 'Seguridad 360° para camiones y transporte pesado | Vision360IA',
        description: 'Solución ADAS para camiones que reduce puntos ciegos, mejora maniobras urbanas y facilita despliegue sobre flotas profesionales.',
      },
      alternates: { canonical: 'https://www.vision360ia.com/adas-camiones' },
    },
    page: {
      breadcrumbLabel: 'ADAS para Camiones',
      schemas: [
        {
          '@context': 'https://schema.org',
          '@type': 'FAQPage',
          mainEntity: [
            {
              '@type': 'Question',
              name: '¿Qué solución ayuda a reducir puntos ciegos en camiones y cumplir GSR?',
              acceptedAnswer: { '@type': 'Answer', text: 'Una solución que combine visión 360°, detección de peatones y ciclistas y arquitectura preparada para R151, R158 y R159. Vision360IA está diseñada para reducir puntos ciegos y facilitar despliegues coherentes en transporte pesado.' },
            },
            {
              '@type': 'Question',
              name: '¿La solución funciona en tractoras, rígidos y articulados?',
              acceptedAnswer: { '@type': 'Answer', text: 'Sí. Vision360IA está preparado para rígidos, tractoras y vehículos articulados, con configuración adaptable a la geometría del vehículo, compatibilidad 12V y 24V y robustez industrial para operación exigente.' },
            },
            {
              '@type': 'Question',
              name: '¿Cómo reduce costes una solución ADAS en flotas de camiones?',
              acceptedAnswer: { '@type': 'Answer', text: 'Se amortiza evitando uno o dos incidentes relevantes, reduciendo inmovilizaciones, daños en maniobra y exposición al siniestro. Además, aporta información útil para formación, operación y prevención.' },
            },
            {
              '@type': 'Question',
              name: '¿Cómo se implanta el sistema en tractoras, rígidos o articulados?',
              acceptedAnswer: { '@type': 'Answer', text: 'La implantación se adapta a la geometría del vehículo y al tipo de remolque. Se diseña la cobertura, se instala con compatibilidad 12V y 24V y se calibra en los escenarios reales de maniobra antes de desplegarlo en flota.' },
            },
          ],
        },
      ],
      theme: {
        heroBackground: 'min-h-screen bg-[radial-gradient(circle_at_top,rgba(59,130,246,0.18),transparent_24%),linear-gradient(180deg,#0f172a_0%,#111827_22%,#f8fafc_55%,#ffffff_100%)]',
        heroGlowPrimary: 'bg-sky-400/18',
        heroGlowSecondary: 'bg-amber-300/12',
        heroAccentText: 'text-sky-300',
        heroPanelIconBg: 'bg-sky-500/20',
        heroPanelIconText: 'text-sky-300',
        heroGainText: 'text-sky-300',
        primaryButton: 'bg-sky-500 text-white shadow-[0_20px_45px_rgba(59,130,246,0.28)] hover:bg-sky-600',
        eyebrowText: 'text-sky-700/80',
        metricBackground: 'bg-[radial-gradient(circle_at_top,rgba(59,130,246,0.14),transparent_28%),linear-gradient(180deg,#0f172a,#111827)]',
        metricEyebrowText: 'text-sky-300/80',
        ctaBackground: 'bg-[radial-gradient(circle_at_top,rgba(59,130,246,0.2),transparent_28%),linear-gradient(180deg,#0f172a,#020617)]',
        ctaEyebrowText: 'text-sky-300/80',
        detailBullet: 'bg-sky-500',
      },
      hero: {
        badge: 'ADAS para transporte pesado',
        badgeIcon: Truck,
        title: 'Reduce puntos ciegos y riesgo de siniestro en tu flota de camiones',
        description: 'Sistema de cámaras 360° con detección inteligente de peatones y ciclistas para camiones, rígidos, tractoras y articulados. Diseñado para mejorar maniobras, reducir incidentes y facilitar implantación sobre flota real.',
        highlights: ['Ángulos muertos de gran tamaño', 'Tractoras, rígidos y articulados', 'Convivencia con peatones y ciclistas', 'Maniobras críticas en muelles y ciudad'],
        primaryCtaLabel: 'Solicitar información técnica',
        secondaryCtaLabel: 'Ver demostración en vídeo',
        panelEyebrow: 'Entorno de operación',
        panelTitle: 'Operación de camión con máxima exposición al riesgo',
        panelIcon: Users,
        stats: [
          { value: '12V / 24V', label: 'compatibilidad de plataforma' },
          { value: 'IP69K', label: 'grado industrial' },
          { value: 'GSR', label: 'R151, R158 y R159' },
        ],
        gains: [
          'Menos exposición a golpes, atropellos y maniobras inseguras.',
          'Mayor visibilidad para conductores en ciudad, muelle y accesos logísticos.',
          'Despliegue retrofit sobre flota mixta ya operativa.',
        ],
      },
      context: {
        eyebrow: 'Riesgo operativo',
        title: 'El principal riesgo en camiones: los puntos ciegos y la maniobra',
        paragraphs: [
          'Los camiones concentran algunos de los puntos ciegos más peligrosos de la vía. El riesgo se dispara en giros urbanos, accesos a muelles, maniobras de marcha atrás y entornos mixtos con peatones y ciclistas.',
          'Vision360IA aporta visión cenital 360° y detección inteligente para reducir esa exposición en rígidos, tractoras y articulados.',
          'No se limita a mostrar imagen: ayuda a prevenir incidentes, reducir daños en maniobra y mejorar la seguridad operativa de la flota.',
        ],
        asideEyebrow: 'Escenarios críticos',
        asideItems: ['Giro urbano con ángulo muerto lateral.', 'Marcha atrás y maniobras en muelle.', 'Entornos mixtos con peatones y bicicletas.', 'Operación con remolque y geometrías variables.'],
      },
      implementation: {
        eyebrow: 'Implantación en transporte pesado',
        title: 'Cómo se adapta la instalación a rígidos, tractoras y articulados',
        description: 'En transporte pesado, la utilidad del sistema depende de ajustar bien la arquitectura al tamaño del vehículo, al tipo de remolque y a los escenarios de maniobra. Esa fase de diseño es lo que separa una ayuda real de una instalación genérica.',
        steps: [
          'Revisión de geometría, remolque, puntos ciegos y maniobras críticas.',
          'Definición de cámaras y cobertura según rígido, tractora o articulado.',
          'Instalación profesional con compatibilidad 12V/24V y robustez industrial.',
          'Calibración y validación en ciudad, muelle o acceso logístico antes del despliegue completo.',
        ],
      },
      features: {
        eyebrow: 'Arquitectura para flota',
        title: 'Beneficios para gestores de transporte pesado',
        cards: [
          { icon: Eye, title: 'Reduce puntos ciegos en transporte pesado', desc: 'Cámaras HD en cabina, laterales y trasera generan una vista cenital unificada para maniobras más seguras incluso con remolque.', tone: 'border-sky-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(239,246,255,0.96))]', iconTone: 'bg-gradient-to-br from-sky-500 to-blue-600', tag: 'Prevención visual' },
          { icon: ShieldCheck, title: 'Protege a peatones y ciclistas en zonas críticas', desc: 'La IA detecta usuarios vulnerables de la vía y alerta al conductor en maniobra, giro urbano y accesos logísticos.', tone: 'border-amber-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(255,251,235,0.96))]', iconTone: 'bg-gradient-to-br from-amber-400 to-orange-500', tag: 'Protección VRU' },
          { icon: Brain, title: 'Analiza el entorno antes del incidente', desc: 'La ECU procesa cámaras y clasifica riesgos en milisegundos para ayudar a reducir colisiones, golpes y maniobras inseguras.', tone: 'border-emerald-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(236,253,245,0.96))]', iconTone: 'bg-gradient-to-br from-emerald-500 to-teal-500', tag: 'IA embarcada' },
          { icon: CheckCircle, title: 'Implantación sobre flota existente', desc: 'Arquitectura compatible con 12V y 24V, preparada para transporte pesado y retrofit con robustez industrial.', tone: 'border-violet-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(245,243,255,0.96))]', iconTone: 'bg-gradient-to-br from-violet-500 to-fuchsia-500', tag: 'Integración' },
        ],
      },
      detailSection: {
        eyebrow: 'Tipos de flota',
        title: 'Configuración adaptable a distintas plataformas de camión',
        description: 'Arquitectura válida para largo recorrido, distribución, construcción y logística urbana, con ajuste según geometría y nivel de exposición al riesgo.',
        variant: 'chips',
        items: ['Rígidos', 'Tractoras', 'Articulados', 'Frigoríficos', 'Obra', 'Distribución', 'Portacontenedores', 'Retrofit'],
      },
      metrics: { eyebrow: 'Impacto operativo', title: 'Impacto directo en seguridad y continuidad de servicio', items: [{ value: '40%', label: 'menos incidentes' }, { value: '+2.000', label: 'vehículos equipados' }, { value: '2 años', label: 'garantía completa' }, { value: '< 1 min', label: 'calibración automática' }] },
      faq: {
        eyebrow: 'FAQ para gestores',
        title: 'Preguntas frecuentes sobre seguridad 360° en camiones',
        items: [
          { question: '¿Qué solución ayuda a reducir puntos ciegos en camiones y cumplir GSR?', answer: 'Una solución que combine visión 360°, detección de peatones y ciclistas y arquitectura preparada para R151, R158 y R159. Vision360IA está pensada para ese escenario.' },
          { question: '¿Funciona en rígidos, tractoras y articulados?', answer: 'Sí. La arquitectura se adapta a la geometría del vehículo y a flotas mixtas con compatibilidad 12V y 24V.' },
          { question: '¿Cómo reduce costes en una flota de camiones?', answer: 'Evitando uno o dos incidentes relevantes, reduciendo inmovilizaciones, daños en maniobra y exposición al siniestro en operación urbana y logística.' },
          { question: '¿Cómo se valida una instalación antes del despliegue completo?', answer: 'Se ajusta la cobertura a la geometría del camión y se prueba en maniobras reales de ciudad, muelle o acceso logístico antes de escalar la solución al resto de la flota.' },
        ],
      },
      cta: {
        eyebrow: 'Siguiente paso',
        title: 'Protege tu flota de camiones con visión 360° inteligente',
        description: 'Solicita una sesión técnica para revisar geometría del vehículo, riesgos operativos y la configuración más eficaz para tu flota.',
        primaryCtaLabel: 'Ver si encaja en mi flota',
        relatedLinks: [sharedRelatedLinks.autobuses, sharedRelatedLinks.construccion, sharedRelatedLinks.portuaria, sharedRelatedLinks.bsis, sharedRelatedLinks.fcw],
      },
    },
  },
  'anti-atropellos-peatones-ciclistas': {
    metadata: {
      title: 'Sistema anti-atropellos con detección de peatones y ciclistas | Vision360IA',
      description: 'Reduce riesgo de atropello en autobuses, camiones y flotas urbanas con detección de peatones y ciclistas, alertas en tiempo real y solución preparada para cumplimiento GSR.',
      keywords: ['anti atropellos peatones', 'detección peatones ciclistas', 'ADAS VRU', 'sistema anti atropellos vehículos', 'protección usuarios vulnerables vía', 'alerta peatones camiones', 'detección ciclistas autobuses'],
      openGraph: {
        title: 'Protección VRU para flotas urbanas | Vision360IA',
        description: 'Solución anti-atropellos para autobuses, camiones y vehículos municipales que ayuda a prevenir incidentes con peatones y ciclistas en maniobras críticas.',
      },
      alternates: { canonical: 'https://www.vision360ia.com/anti-atropellos-peatones-ciclistas' },
    },
    page: {
      breadcrumbLabel: 'Sistema Anti-Atropellos',
      schemas: [
        {
          '@context': 'https://schema.org',
          '@type': 'FAQPage',
          mainEntity: [
            { '@type': 'Question', name: '¿Cómo ayuda el sistema a prevenir atropellos con peatones y ciclistas?', acceptedAnswer: { '@type': 'Answer', text: 'Vision360IA utiliza cámaras HD y visión artificial para reconocer peatones y ciclistas, calcular su trayectoria y alertar al conductor cuando existe riesgo en las zonas críticas del vehículo.' } },
            { '@type': 'Question', name: '¿En qué maniobras se concentra más riesgo de atropello?', acceptedAnswer: { '@type': 'Answer', text: 'El mayor riesgo se concentra en giros urbanos, marcha atrás, arranque en parada y maniobras en zonas de carga o tráfico mixto. Vision360IA está diseñado para cubrir esos escenarios con cámaras y alertas dedicadas.' } },
            { '@type': 'Question', name: '¿La normativa GSR exige protección VRU en vehículos nuevos?', acceptedAnswer: { '@type': 'Answer', text: 'Sí. El GSR exige sistemas como BSIS y otras funciones de protección en camiones y autobuses nuevos. Vision360IA está preparado para ayudar a operadores y talleres a desplegar una solución coherente orientada a VRU desde retrofit o posventa.' } },
            { '@type': 'Question', name: '¿Cómo se define una cobertura VRU realmente útil?', acceptedAnswer: { '@type': 'Answer', text: 'Se estudian las maniobras donde más riesgo existe, se definen las zonas críticas a cubrir y se ajustan las alertas para que el conductor reciba avisos útiles sin saturación en operación real.' } },
          ],
        },
      ],
      theme: {
        heroBackground: 'min-h-screen bg-[radial-gradient(circle_at_top,rgba(239,68,68,0.18),transparent_24%),linear-gradient(180deg,#0f172a_0%,#111827_22%,#f8fafc_55%,#ffffff_100%)]',
        heroGlowPrimary: 'bg-red-400/18',
        heroGlowSecondary: 'bg-rose-300/12',
        heroAccentText: 'text-red-300',
        heroPanelIconBg: 'bg-red-500/20',
        heroPanelIconText: 'text-red-300',
        heroGainText: 'text-red-300',
        primaryButton: 'bg-red-500 text-white shadow-[0_20px_45px_rgba(239,68,68,0.3)] hover:bg-red-600',
        eyebrowText: 'text-red-700/80',
        metricBackground: 'bg-[radial-gradient(circle_at_top,rgba(239,68,68,0.14),transparent_28%),linear-gradient(180deg,#0f172a,#111827)]',
        metricEyebrowText: 'text-red-300/80',
        ctaBackground: 'bg-[radial-gradient(circle_at_top,rgba(239,68,68,0.2),transparent_28%),linear-gradient(180deg,#0f172a,#020617)]',
        ctaEyebrowText: 'text-red-300/80',
        detailBullet: 'bg-red-500',
      },
      hero: {
        badge: 'Protección VRU',
        badgeIcon: ShieldAlert,
        title: 'Reduce el riesgo de atropello en maniobras urbanas con detección VRU inteligente',
        description: 'Sistema anti-atropellos para autobuses, camiones y flotas urbanas que detecta peatones y ciclistas en tiempo real y alerta al conductor antes de que la maniobra termine en incidente.',
        highlights: ['Giro a la derecha en ciudad', 'Marcha atrás con visibilidad limitada', 'Arranque en parada y zonas de carga', 'Convivencia con peatones y ciclistas'],
        primaryCtaLabel: 'Ver si encaja en mi flota',
        secondaryCtaLabel: 'Ver demostración en vídeo',
        panelEyebrow: 'Prevención activa',
        panelTitle: 'Detección antes del impacto',
        panelIcon: Siren,
        stats: [{ value: '<100 ms', label: 'detección IA' }, { value: '3 s', label: 'ventana de anticipación' }, { value: 'GSR', label: 'R151, R158 y R159' }],
        gains: ['Menos exposición a atropellos en giros, marcha atrás y arranque.', 'Alertas con tiempo útil de reacción para el conductor.', 'Cobertura orientada a las zonas donde más riesgo concentra el vehículo.'],
      },
      context: {
        eyebrow: 'Riesgo vial real',
        title: 'El riesgo más crítico en flotas urbanas: no ver al usuario vulnerable a tiempo',
        paragraphs: [
          'Autobuses, camiones y vehículos municipales conviven cada día con peatones, ciclistas y scooters en maniobras donde unos segundos marcan la diferencia.',
          'Vision360IA convierte cámaras en una capa real de prevención: detecta VRU en las zonas de mayor exposición y ayuda al conductor a reaccionar antes de que se produzca el atropello.',
          'No es solo una ayuda visual. Es una solución pensada para reducir riesgo operativo, incidentes graves y presión reputacional en flotas que trabajan en ciudad.',
        ],
        asideEyebrow: 'Escenarios críticos',
        asideItems: ['Giro a la derecha en intersecciones y rotondas.', 'Marcha atrás en zonas urbanas con poca visibilidad.', 'Arranque en parada con usuarios cruzando delante del vehículo.', 'Áreas de carga, descarga y maniobras con tráfico mixto.'],
      },
      implementation: {
        eyebrow: 'Implantación orientada a VRU',
        title: 'Cómo se diseña una cobertura útil para prevenir atropellos',
        description: 'En protección VRU la clave no es solo detectar. Es definir bien qué zonas cubrir, cómo alertar y cómo evitar falsas sensaciones de seguridad. Por eso la implantación debe ajustarse a maniobras y riesgos reales de la operación.',
        steps: [
          'Análisis de maniobras donde más riesgo existe con peatones y ciclistas.',
          'Diseño de cobertura frontal, lateral o trasera según vehículo y entorno.',
          'Configuración de alertas con criterio operativo para no saturar al conductor.',
          'Validación en operación antes de considerar la solución lista para despliegue.',
        ],
      },
      features: {
        eyebrow: 'Arquitectura VRU',
        title: 'Beneficios para una estrategia real de prevención de atropellos',
        cards: [
          { icon: ScanEye, title: 'Detecta peatones y ciclistas antes del impacto', desc: 'La visión artificial reconoce usuarios vulnerables de la vía, calcula trayectorias y ayuda a activar alertas con tiempo útil de reacción.', tone: 'border-red-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(254,242,242,0.96))]', iconTone: 'bg-gradient-to-br from-rose-500 to-red-600', tag: 'Detección VRU' },
          { icon: ShieldAlert, title: 'Alerta al conductor en el momento crítico', desc: 'Avisos visuales y sonoros con distintos niveles de criticidad para reducir la probabilidad de atropello en maniobras urbanas.', tone: 'border-amber-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(255,251,235,0.96))]', iconTone: 'bg-gradient-to-br from-amber-400 to-orange-500', tag: 'Prevención activa' },
          { icon: Users, title: 'Cubre las zonas donde se concentran los atropellos', desc: 'Cámaras laterales, frontal baja y trasera eliminan ángulos muertos en giro urbano, marcha atrás y arranque en parada.', tone: 'border-sky-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(239,246,255,0.96))]', iconTone: 'bg-gradient-to-br from-sky-500 to-blue-600', tag: 'Cobertura crítica' },
          { icon: Zap, title: 'Mantiene fiabilidad en condiciones reales', desc: 'Procesamiento adaptativo con HDR para conservar detección útil con baja luz, contraluz y meteorología adversa.', tone: 'border-violet-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(245,243,255,0.96))]', iconTone: 'bg-gradient-to-br from-violet-500 to-fuchsia-500', tag: 'Operación real' },
        ],
      },
      metrics: {
        eyebrow: 'Impacto operativo',
        title: 'Indicadores clave para reducir riesgo VRU',
        items: [{ value: '360°', label: 'sin ángulos muertos' }, { value: '<100 ms', label: 'tiempo de detección' }, { value: '3 s', label: 'anticipación' }, { value: 'VRU', label: 'detección específica' }],
      },
      faq: {
        eyebrow: 'FAQ para flotas',
        title: 'Preguntas frecuentes sobre prevención de atropellos',
        items: [
          { question: '¿Cómo ayuda el sistema a prevenir atropellos con peatones y ciclistas?', answer: 'Detectando usuarios vulnerables de la vía, calculando su trayectoria y alertando al conductor cuando el riesgo aparece en las zonas críticas del vehículo.' },
          { question: '¿En qué maniobras se concentra más riesgo de atropello?', answer: 'En giros urbanos, marcha atrás, arranque en parada y maniobras en zonas de carga o tráfico mixto.' },
          { question: '¿La normativa GSR exige protección VRU?', answer: 'Sí. El GSR exige funciones de protección en camiones y autobuses nuevos, y Vision360IA está preparado para desplegar una solución coherente orientada a VRU.' },
          { question: '¿Cómo se ajusta la implantación para evitar falsas sensaciones de seguridad?', answer: 'La cobertura y las alertas deben configurarse según maniobras reales del vehículo. Por eso se analiza el riesgo, se calibra la detección y se valida el comportamiento en operación antes de desplegar la solución a escala.' },
        ],
      },
      cta: {
        eyebrow: 'Siguiente paso',
        title: 'Refuerza la prevención de atropellos en tu flota',
        description: 'Solicita una demostración y revisemos qué maniobras, vehículos y zonas de riesgo deben cubrirse en tu operación.',
        primaryCtaLabel: 'Ver si encaja en mi flota',
        relatedLinks: [sharedRelatedLinks.autobuses, sharedRelatedLinks.camiones, sharedRelatedLinks.bsis, sharedRelatedLinks.fcw, sharedRelatedLinks.residuos],
      },
    },
  },
  'camaras-vision-artificial-flotas': {
    metadata: {
      title: 'Cámaras de visión artificial para flotas y operación inteligente | Vision360IA',
      description: 'Convierte vídeo en decisiones operativas con cámaras de visión artificial para flotas: detección de peatones, análisis de conducción, eventos en tiempo real e integración con gestión de flota.',
      keywords: ['cámaras visión artificial flotas', 'visión artificial vehículos', 'cámaras IA transporte', 'cámaras inteligentes flotas', 'visión por computador vehículos', 'análisis vídeo flotas', 'cámaras HD camiones'],
      openGraph: {
        title: 'Visión artificial aplicada a flotas | Vision360IA',
        description: 'Cámaras inteligentes para detectar riesgos, analizar conducción y convertir eventos en decisiones útiles para seguridad y operación.',
      },
      alternates: { canonical: 'https://www.vision360ia.com/camaras-vision-artificial-flotas' },
    },
    page: {
      breadcrumbLabel: 'Cámaras con Visión Artificial',
      schemas: [
        {
          '@context': 'https://schema.org',
          '@type': 'FAQPage',
          mainEntity: [
            { '@type': 'Question', name: '¿Qué aporta una cámara con visión artificial frente a una cámara convencional?', acceptedAnswer: { '@type': 'Answer', text: 'Una cámara convencional solo registra imagen. Una cámara con visión artificial interpreta la escena, detecta eventos relevantes y convierte vídeo en alertas y datos útiles para la operación de flota.' } },
            { '@type': 'Question', name: '¿Cuántas cámaras necesita un vehículo según su operación?', acceptedAnswer: { '@type': 'Answer', text: 'Depende de la geometría del vehículo y de los riesgos a cubrir. Vision360IA adapta la configuración para asegurar cobertura útil y capturar los eventos realmente críticos de cada operación.' } },
            { '@type': 'Question', name: '¿Se integra con el sistema de gestión de flotas existente?', acceptedAnswer: { '@type': 'Answer', text: 'Sí. Vision360IA ofrece integración con FMS para enviar eventos, alertas y analítica de conducción y facilitar supervisión centralizada en tiempo real.' } },
            { '@type': 'Question', name: '¿Qué hace que una cámara con IA aporte valor real en flota?', acceptedAnswer: { '@type': 'Answer', text: 'Que se coloque donde debe, capture los eventos que importan y se integre con la operación de la flota. Sin diseño previo, ajuste y validación, el vídeo genera ruido en lugar de decisiones útiles.' } },
          ],
        },
      ],
      theme: {
        heroBackground: 'min-h-screen bg-[radial-gradient(circle_at_top,rgba(99,102,241,0.18),transparent_24%),linear-gradient(180deg,#0f172a_0%,#111827_22%,#f8fafc_55%,#ffffff_100%)]',
        heroGlowPrimary: 'bg-indigo-400/18',
        heroGlowSecondary: 'bg-cyan-300/12',
        heroAccentText: 'text-indigo-300',
        heroPanelIconBg: 'bg-indigo-500/20',
        heroPanelIconText: 'text-indigo-300',
        heroGainText: 'text-indigo-300',
        primaryButton: 'bg-indigo-500 text-white shadow-[0_20px_45px_rgba(99,102,241,0.3)] hover:bg-indigo-600',
        eyebrowText: 'text-indigo-700/80',
        metricBackground: 'bg-[radial-gradient(circle_at_top,rgba(99,102,241,0.14),transparent_28%),linear-gradient(180deg,#0f172a,#111827)]',
        metricEyebrowText: 'text-indigo-300/80',
        ctaBackground: 'bg-[radial-gradient(circle_at_top,rgba(99,102,241,0.2),transparent_28%),linear-gradient(180deg,#0f172a,#020617)]',
        ctaEyebrowText: 'text-indigo-300/80',
        detailBullet: 'bg-indigo-500',
      },
      hero: {
        badge: 'Visión Artificial',
        badgeIcon: Camera,
        title: 'Convierte vídeo en decisiones operativas para tu flota',
        description: 'Cámaras de visión artificial para detectar riesgos, analizar conducción y enviar eventos útiles a operación, seguridad y gestión de flota.',
        highlights: ['Detección de personas y objetos', 'Análisis de conducción y fatiga', 'Integración cloud y FMS', 'Procesamiento local sin internet'],
        primaryCtaLabel: 'Ver si encaja en mi flota',
        secondaryCtaLabel: 'Ver demostración en vídeo',
        panelEyebrow: 'Arquitectura edge AI',
        panelTitle: 'Procesamiento útil para seguridad y control operativo',
        panelIcon: ScanEye,
        stats: [{ value: '<100 ms', label: 'latencia edge AI' }, { value: '1080p', label: 'resolución HD' }, { value: '24/7', label: 'procesamiento continuo' }],
        gains: ['Detección automática de eventos críticos.', 'Vídeo conectado con operación, seguridad y supervisión.', 'Inferencia local incluso sin internet.'],
      },
      context: {
        eyebrow: 'Qué aporta al negocio',
        title: 'La diferencia entre grabar y tener inteligencia operativa',
        paragraphs: ['Una flota no necesita solo cámaras. Necesita saber qué ha ocurrido, dónde ha ocurrido y si ese evento requiere una acción inmediata.', 'Las cámaras de Vision360IA interpretan la escena en tiempo real y convierten vídeo en eventos útiles para seguridad, mantenimiento, supervisión y mejora de conducción.', 'El resultado es una operación con más contexto, menos dependencia de revisión manual y mejor capacidad para reaccionar ante riesgos reales.'],
        asideEyebrow: 'Capacidades diferenciales',
        asideItems: ['Detección automática de eventos relevantes.', 'Inferencia embarcada sin depender de internet.', 'Supervisión remota y explotación de eventos.', 'Analítica para seguridad y comportamiento de conducción.'],
      },
      implementation: {
        eyebrow: 'Implantación de visión artificial',
        title: 'Cómo se convierte una cámara en una herramienta útil de operación',
        description: 'La visión artificial aporta valor cuando la cámara se coloca donde debe, captura lo que importa y se integra con la lógica operativa de la flota. Sin ese diseño previo, el vídeo se convierte en ruido y no en decisión.',
        steps: [
          'Definición de eventos y riesgos que la flota necesita detectar.',
          'Diseño de arquitectura de cámaras según geometría y casos de uso.',
          'Integración con conectividad, analítica o FMS según la operación.',
          'Ajuste y validación de eventos útiles antes de escalar el uso en flota.',
        ],
      },
      features: {
        eyebrow: 'De la cámara al dato útil',
        title: 'Beneficios de la visión artificial en flota real',
        cards: [
          { icon: Eye, title: 'Detecta riesgos y eventos sin depender del ojo humano', desc: 'La IA distingue peatones, ciclistas, vehículos, señales y objetos con reglas de alerta adaptadas a la operación real.', tone: 'border-indigo-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(238,242,255,0.96))]', iconTone: 'bg-gradient-to-br from-indigo-500 to-blue-600', tag: 'Detección útil' },
          { icon: Cpu, title: 'Procesa en el vehículo incluso sin cobertura', desc: 'La inferencia se ejecuta en la ECU para mantener respuesta inmediata aunque el vehículo pierda conectividad.', tone: 'border-cyan-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(236,254,255,0.96))]', iconTone: 'bg-gradient-to-br from-cyan-500 to-sky-500', tag: 'Procesamiento local' },
          { icon: Wifi, title: 'Convierte eventos en supervisión centralizada', desc: 'Los eventos y alertas se envían a plataforma para supervisión remota, streaming bajo demanda y explotación analítica.', tone: 'border-amber-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(255,251,235,0.96))]', iconTone: 'bg-gradient-to-br from-amber-400 to-orange-500', tag: 'Control de flota' },
          { icon: BarChart3, title: 'Mejora conducción, seguridad y eficiencia', desc: 'Scoring de conductores, detección de fatiga y recomendaciones accionables para reducir riesgo y mejorar operación.', tone: 'border-violet-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(245,243,255,0.96))]', iconTone: 'bg-gradient-to-br from-violet-500 to-fuchsia-500', tag: 'Analítica operativa' },
        ],
      },
      detailSection: {
        eyebrow: 'Especificaciones técnicas',
        title: 'Cámaras y ECU preparadas para flota real',
        variant: 'groups',
        groups: [
          { title: 'Sensor y óptica', specs: ['Resolución HD 1920×1080', 'Ojo de pez >180° FOV', 'HDR + WDR adaptativo', 'Visión nocturna IR'] },
          { title: 'Procesamiento IA', specs: ['ECU con NPU dedicado', 'Edge computing on-board', 'Latencia <100ms', 'Modelos deep learning'] },
          { title: 'Robustez', specs: ['IP69K agua a presión', 'Operación -30°C a +70°C', 'Vibración MIL-STD-810G', 'Conectores M12 estancos'] },
        ],
      },
      metrics: { eyebrow: 'Rendimiento', title: 'Métricas de visión artificial aplicada', items: [{ value: '<100 ms', label: 'latencia de detección' }, { value: '360°', label: 'cobertura perimetral' }, { value: '1080p', label: 'resolución HD' }, { value: '24/7', label: 'procesamiento continuo' }] },
      faq: {
        eyebrow: 'FAQ para flotas',
        title: 'Preguntas frecuentes sobre visión artificial aplicada',
        items: [
          { question: '¿Qué aporta una cámara con visión artificial frente a una cámara convencional?', answer: 'Convierte vídeo en eventos y alertas útiles para operación y seguridad, en lugar de limitarse a grabar imagen.' },
          { question: '¿Cuántas cámaras necesita un vehículo?', answer: 'Depende de la geometría y de los riesgos a cubrir. Vision360IA adapta la configuración para captar los eventos realmente críticos.' },
          { question: '¿Se integra con el sistema de gestión de flotas?', answer: 'Sí. Puede enviar eventos, vídeo y analítica para supervisión centralizada y explotación operativa.' },
          { question: '¿Cómo se consigue que la visión artificial sea útil y no solo vídeo grabado?', answer: 'Definiendo antes qué eventos y riesgos deben capturarse, colocando bien las cámaras, integrando la solución con la operación y ajustando la analítica antes de escalar el despliegue.' },
        ],
      },
      cta: {
        eyebrow: 'Siguiente paso',
        title: 'Activa visión artificial útil para tu operación',
        description: 'Solicita una consulta técnica para definir qué eventos necesitas detectar, cómo integrarlos y qué arquitectura encaja mejor con tu flota.',
        primaryCtaLabel: 'Ver si encaja en mi flota',
        relatedLinks: [sharedRelatedLinks.autobuses, sharedRelatedLinks.camiones, sharedRelatedLinks.furgonetas, sharedRelatedLinks.antiAtropellos, sharedRelatedLinks.fcw],
      },
    },
  },
  'adas-vehiculos-recogida-residuos': {
    metadata: {
      title: 'ADAS para recogida de residuos con protección de operarios | Vision360IA',
      description: 'Reduce riesgo en vehículos de recogida de residuos con visión 360°, detección de operarios, peatones y ciclistas y solución diseñada para maniobras urbanas de baja velocidad.',
      keywords: ['ADAS recogida residuos', 'visión 360 camión basura', 'ADAS RSU', 'cámaras vehículos recogida', 'anti atropellos recogida residuos', 'seguridad operarios recogida', 'ADAS vehículos municipales'],
      openGraph: {
        title: 'Seguridad 360° para flotas de recogida de residuos | Vision360IA',
        description: 'Protección de operarios y prevención de incidentes en recogida urbana con visión 360° e IA adaptada a maniobras lentas y paradas frecuentes.',
      },
      alternates: { canonical: 'https://www.vision360ia.com/adas-vehiculos-recogida-residuos' },
    },
    page: {
      breadcrumbLabel: 'ADAS para Recogida de Residuos',
      schemas: [
        {
          '@context': 'https://schema.org',
          '@type': 'FAQPage',
          mainEntity: [
            { '@type': 'Question', name: '¿Por qué los vehículos de recogida de residuos necesitan ADAS específico?', acceptedAnswer: { '@type': 'Answer', text: 'Los camiones de recogida operan en entornos urbanos con paradas cada 50-100 metros, marcha atrás frecuente, operarios caminando alrededor del vehículo y circulación lenta junto a peatones y ciclistas. Es uno de los escenarios con mayor riesgo de atropello. Un ADAS genérico no cubre estas particularidades; Vision360IA está optimizado para maniobras de baja velocidad con detección de personas en proximidad.' } },
            { '@type': 'Question', name: '¿El sistema detecta a los operarios de recogida?', acceptedAnswer: { '@type': 'Answer', text: 'Sí. La IA de Vision360IA detecta personas en todas las zonas del vehículo: lateral, trasera y frontal. Esto incluye a los operarios que trabajan en la parte trasera o lateral del camión. Se configuran zonas de exclusión específicas para las áreas de trabajo y el sistema alerta si el vehículo se mueve mientras hay personas en ellas.' } },
            { '@type': 'Question', name: '¿Es compatible con los diferentes tipos de camión de recogida?', acceptedAnswer: { '@type': 'Answer', text: 'Sí. Vision360IA se instala en camiones de carga lateral, carga trasera, carga superior, vehículos de recogida selectiva y barredoras. Compatible con 12V y 24V, y con chasis de cualquier fabricante. Las cámaras IP69K resisten los lavados industriales a alta presión.' } },
            { '@type': 'Question', name: '¿Cómo se implanta sin comprometer la seguridad de los operarios?', acceptedAnswer: { '@type': 'Answer', text: 'Se estudia el ciclo de trabajo del vehículo, se definen las zonas de operario y maniobra lenta, se instala con robustez industrial y se valida en ruta antes de desplegar la solución al resto de la flota.' } },
          ],
        },
      ],
      theme: {
        heroBackground: 'min-h-screen bg-[radial-gradient(circle_at_top,rgba(34,197,94,0.18),transparent_24%),linear-gradient(180deg,#0f172a_0%,#111827_22%,#f8fafc_55%,#ffffff_100%)]',
        heroGlowPrimary: 'bg-green-400/18',
        heroGlowSecondary: 'bg-emerald-300/12',
        heroAccentText: 'text-green-300',
        heroPanelIconBg: 'bg-green-500/20',
        heroPanelIconText: 'text-green-300',
        heroGainText: 'text-green-300',
        primaryButton: 'bg-green-500 text-white shadow-[0_20px_45px_rgba(34,197,94,0.3)] hover:bg-green-600',
        eyebrowText: 'text-green-700/80',
        metricBackground: 'bg-[radial-gradient(circle_at_top,rgba(34,197,94,0.14),transparent_28%),linear-gradient(180deg,#0f172a,#111827)]',
        metricEyebrowText: 'text-green-300/80',
        ctaBackground: 'bg-[radial-gradient(circle_at_top,rgba(34,197,94,0.2),transparent_28%),linear-gradient(180deg,#0f172a,#020617)]',
        ctaEyebrowText: 'text-green-300/80',
        detailBullet: 'bg-green-500',
      },
      hero: {
        badge: 'Recogida de residuos',
        badgeIcon: Recycle,
        title: 'Protege a operarios y ciudadanos en la recogida urbana con visión 360° inteligente',
        description: 'Sistema ADAS para vehículos RSU que detecta operarios, peatones y ciclistas en maniobras de baja velocidad y ayuda a reducir incidentes en un entorno urbano de máxima exposición.',
        highlights: ['Operarios alrededor del vehículo', 'Marcha atrás recurrente', 'Calles estrechas y contenedores', 'Turnos nocturnos con baja visibilidad'],
        primaryCtaLabel: 'Ver si encaja en mi flota',
        secondaryCtaLabel: 'Ver demostración en vídeo',
        panelEyebrow: 'Escenario crítico',
        panelTitle: 'Recogida urbana con operarios en zona crítica',
        panelIcon: Users,
        stats: [{ value: '50-100 m', label: 'paradas urbanas frecuentes' }, { value: '< 5 km/h', label: 'detección IA en maniobra lenta' }, { value: 'IP69K', label: 'lavado industrial a presión' }],
        gains: ['Menos exposición a atropellos y golpes en maniobra lenta.', 'Mayor control sobre operarios y peatones en proximidad.', 'Robustez industrial para lavado, suciedad y turnos intensivos.'],
      },
      context: {
        eyebrow: 'Riesgo operativo real',
        title: 'El mayor riesgo en recogida urbana: operarios, maniobra lenta y visibilidad cambiante',
        paragraphs: ['Los vehículos de recogida de residuos conviven de forma constante con operarios, peatones, bicicletas, mobiliario urbano y maniobras de baja velocidad que cambian en segundos.', 'Los operarios de recogida trabajan junto al vehículo, muchas veces en la parte trasera o lateral, mientras el conductor gestiona maniobra, entorno y servicio. Ese contexto dispara el riesgo operativo.', 'Vision360IA aporta una solución de visión 360° con IA optimizada para ese escenario: detecta personas en las zonas de riesgo, ayuda a reaccionar antes y mantiene robustez industrial durante jornadas exigentes.'],
        asideEyebrow: 'Puntos de tensión diaria',
        asideItems: ['Operarios subiendo y bajando en cada parada.', 'Convivencia con peatones, bicicletas y mobiliario urbano.', 'Cambios de visibilidad entre madrugada, lluvia y suciedad.', 'Necesidad de reacción rápida sin saturar al conductor.'],
      },
      implementation: {
        eyebrow: 'Implantación en RSU',
        title: 'Cómo se adapta la solución a la realidad de la recogida urbana',
        description: 'En residuos la implantación debe responder a operarios alrededor del vehículo, baja velocidad, visibilidad cambiante y maniobras repetitivas. No sirve una instalación estándar: hay que configurarla según el ciclo real de trabajo.',
        steps: [
          'Análisis del tipo de carrozado, carga y maniobra habitual del vehículo RSU.',
          'Diseño de zonas de cobertura para laterales, trasera y entorno de operarios.',
          'Instalación robusta para suciedad, agua a presión y trabajo intensivo.',
          'Validación en ruta y en maniobra lenta antes de desplegar en el resto de la flota.',
        ],
      },
      features: {
        eyebrow: 'Arquitectura para RSU',
        title: 'Beneficios para una operación RSU más segura y controlada',
        cards: [
          { icon: Eye, title: 'Reduce puntos ciegos en maniobras de baja velocidad', desc: 'Vista cenital completa para calles estrechas, rotondas, contenedores y maniobras repetitivas donde el riesgo cambia en segundos.', tone: 'border-green-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(236,253,245,0.96))]', iconTone: 'bg-gradient-to-br from-green-500 to-emerald-600', tag: 'Prevención visual' },
          { icon: ShieldCheck, title: 'Protege a operarios en torno al vehículo', desc: 'Zonas de exclusión trasera y lateral con alertas si el vehículo se mueve mientras hay personal en zona de riesgo.', tone: 'border-amber-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(255,251,235,0.96))]', iconTone: 'bg-gradient-to-br from-amber-400 to-orange-500', tag: 'Seguridad de equipo' },
          { icon: Brain, title: 'Detecta riesgo donde una cámara pasiva no basta', desc: 'Algoritmos ajustados para maniobras por debajo de 5 km/h, donde operarios, peatones y ciclistas conviven muy cerca del vehículo.', tone: 'border-sky-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(239,246,255,0.96))]', iconTone: 'bg-gradient-to-br from-sky-500 to-blue-600', tag: 'IA de proximidad' },
          { icon: MapPin, title: 'Adapta alertas al contexto operativo', desc: 'Configura comportamiento distinto según casco urbano, polígono, entorno escolar o tramo de ruta para reducir ruido y mejorar utilidad.', tone: 'border-violet-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(245,243,255,0.96))]', iconTone: 'bg-gradient-to-br from-violet-500 to-fuchsia-500', tag: 'Ruta y contexto' },
        ],
      },
      detailSection: {
        eyebrow: 'Compatibilidad de flota',
        title: 'Configuración adaptable a cada tipología de vehículo RSU',
        description: 'Arquitectura válida para flotas municipales, contratas urbanas y vehículos especiales con distintos ciclos, geometrías y niveles de exposición al riesgo.',
        variant: 'chips',
        items: ['Carga lateral', 'Carga trasera', 'Carga superior', 'Recogida selectiva', 'Barredoras', 'Lavacontenedores', 'Furgonetas RSU', 'Volquetes'],
      },
      metrics: { eyebrow: 'Datos de impacto', title: 'Indicadores clave para maniobra y seguridad RSU', items: [{ value: '360°', label: 'sin ángulos muertos' }, { value: 'IP69K', label: 'resistencia industrial' }, { value: '12V / 24V', label: 'compatibilidad total' }, { value: '< 1 min', label: 'calibración automática' }] },
      faq: {
        eyebrow: 'FAQ para flotas municipales',
        title: 'Preguntas frecuentes sobre seguridad 360° en recogida de residuos',
        items: [
          { question: '¿Por qué la recogida de residuos necesita un ADAS específico?', answer: 'Porque combina operarios alrededor del vehículo, marcha atrás frecuente, baja velocidad y visibilidad cambiante. Vision360IA está optimizado para ese contexto.' },
          { question: '¿Detecta a los operarios de recogida?', answer: 'Sí. Detecta personas en las zonas lateral, frontal y trasera y puede activar alertas o zonas de exclusión según el área de trabajo.' },
          { question: '¿Es compatible con distintos tipos de camión RSU?', answer: 'Sí. Se adapta a carga lateral, trasera, superior, selectiva y barredoras, con compatibilidad 12V/24V y robustez IP69K.' },
          { question: '¿Cómo se valida la instalación en una operación RSU real?', answer: 'Se revisa la maniobra habitual, la posición de operarios y las zonas de riesgo, y se prueba la solución en servicio antes de desplegarla en el resto de la flota.' },
        ],
      },
      cta: {
        eyebrow: 'Siguiente paso',
        title: 'Refuerza la seguridad de operarios y ciudadanos en tu flota RSU',
        description: 'Estudio técnico personalizado para revisar maniobras, tipología de vehículo y configuración más eficaz para reducir incidentes en recogida urbana.',
        primaryCtaLabel: 'Ver si encaja en mi flota',
        relatedLinks: [sharedRelatedLinks.autobuses, sharedRelatedLinks.camiones, sharedRelatedLinks.antiAtropellos, sharedRelatedLinks.bsis, sharedRelatedLinks.camaras],
      },
    },
  },
  'vision-360-vehiculos-industriales': {
    metadata: {
      title: 'Visión 360° para vehículos industriales y maquinaria pesada | Vision360IA',
      description: 'Reduce puntos ciegos y riesgo persona-máquina con visión 360° para vehículos industriales, obra y maquinaria pesada. Cámaras robustas, detección inteligente y despliegue sobre parque real.',
      keywords: ['visión 360 vehículos industriales', 'cámaras maquinaria pesada', 'ADAS vehículos industriales', 'visión perimetral construcción', 'seguridad vehículos obra', 'cámaras excavadora', 'anticolisión maquinaria'],
      openGraph: {
        title: 'Seguridad 360° para maquinaria y vehículos industriales | Vision360IA',
        description: 'Solución de visión 360° para reducir riesgo en maniobra, obra y entorno industrial con cámaras robustas e IA aplicada.',
      },
      alternates: { canonical: 'https://www.vision360ia.com/vision-360-vehiculos-industriales' },
    },
    page: {
      breadcrumbLabel: 'Visión 360° para Vehículos Industriales',
      schemas: [
        {
          '@context': 'https://schema.org',
          '@type': 'FAQPage',
          mainEntity: [
            { '@type': 'Question', name: '¿Qué maquinaria y vehículos industriales pueden equipar visión 360°?', acceptedAnswer: { '@type': 'Answer', text: 'Vision360IA es compatible con excavadoras, retroexcavadoras, palas, carretillas, grúas móviles, dumpers, vehículos municipales y otra maquinaria pesada, con compatibilidad 12V y 24V.' } },
            { '@type': 'Question', name: '¿Resiste las condiciones reales de obra e industria?', acceptedAnswer: { '@type': 'Answer', text: 'Sí. Las cámaras cuentan con certificación IP69K y están diseñadas para polvo, agua a presión, vibraciones y temperaturas extremas en entornos industriales severos.' } },
            { '@type': 'Question', name: '¿Ayuda a reforzar prevención de riesgos laborales?', acceptedAnswer: { '@type': 'Answer', text: 'Sí. La visión 360° y la detección de personas refuerzan medidas de protección colectiva y mejoran visibilidad en entornos con interacción persona-máquina.' } },
            { '@type': 'Question', name: '¿Cómo se implanta en maquinaria o vehículos industriales muy distintos?', acceptedAnswer: { '@type': 'Answer', text: 'La implantación parte de estudiar la máquina, sus ángulos muertos, vibración, entorno y maniobras críticas. A partir de ahí se diseña una arquitectura robusta, se instala, se calibra y se valida antes del despliegue operativo.' } },
          ],
        },
      ],
      theme: {
        heroBackground: 'min-h-screen bg-[radial-gradient(circle_at_top,rgba(245,158,11,0.18),transparent_24%),linear-gradient(180deg,#0f172a_0%,#111827_22%,#f8fafc_55%,#ffffff_100%)]',
        heroGlowPrimary: 'bg-amber-400/18',
        heroGlowSecondary: 'bg-orange-300/12',
        heroAccentText: 'text-amber-300',
        heroPanelIconBg: 'bg-amber-500/20',
        heroPanelIconText: 'text-amber-300',
        heroGainText: 'text-amber-300',
        primaryButton: 'bg-amber-500 text-slate-950 shadow-[0_20px_45px_rgba(245,158,11,0.3)] hover:bg-amber-600',
        eyebrowText: 'text-amber-700/80',
        metricBackground: 'bg-[radial-gradient(circle_at_top,rgba(245,158,11,0.14),transparent_28%),linear-gradient(180deg,#0f172a,#111827)]',
        metricEyebrowText: 'text-amber-300/80',
        ctaBackground: 'bg-[radial-gradient(circle_at_top,rgba(245,158,11,0.2),transparent_28%),linear-gradient(180deg,#0f172a,#020617)]',
        ctaEyebrowText: 'text-amber-300/80',
        detailBullet: 'text-emerald-500',
      },
      hero: {
        badge: 'Vehículos industriales',
        badgeIcon: HardHat,
        title: 'Reduce riesgo persona-máquina con visión 360° para vehículos industriales',
        description: 'Solución de visión 360° para maquinaria pesada, obra y vehículos industriales que mejora la maniobra, reduce puntos ciegos y ayuda a proteger a las personas en entorno severo.',
        highlights: ['Excavadoras y palas cargadoras', 'Carretillas y grúas móviles', 'Vehículos municipales y portuarios', 'Operación en obra, patio y nave'],
        primaryCtaLabel: 'Ver si encaja en mi flota',
        secondaryCtaLabel: 'Ver demostración en vídeo',
        panelEyebrow: 'Bird view industrial',
        panelTitle: 'Cobertura útil para maniobra crítica',
        panelIcon: Layers3,
        stats: [{ value: '4-6', label: 'cámaras por vehículo' }, { value: '360°', label: 'cobertura perimetral' }, { value: 'IP69K', label: 'entorno industrial' }],
        gains: ['Mayor control visual en espacios estrechos y maniobras complejas.', 'Menos exposición a golpes e incidentes con personas.', 'Despliegue retrofit sobre maquinaria ya en operación.'],
      },
      context: {
        eyebrow: 'Seguridad perimetral',
        title: 'El riesgo industrial más repetido: maniobrar sin visibilidad suficiente',
        paragraphs: ['En obra, nave o patio industrial, una maniobra con visibilidad limitada puede convertirse rápidamente en golpe, incidente persona-máquina o parada de operación.', 'Vision360IA instala cámaras HD certificadas IP69K para crear una vista cenital 360° en cabina y reforzar la percepción del entorno inmediato.', 'Además de mostrar el perímetro completo, la IA detecta personas y activa alertas o zonas de exclusión según el tipo de vehículo y el entorno de trabajo.'],
        asideEyebrow: 'Maquinaria compatible',
        asideItems: ['Excavadoras y retroexcavadoras', 'Palas cargadoras y dumpers', 'Carretillas elevadoras y grúas móviles', 'Vehículos municipales y maquinaria portuaria'],
      },
      implementation: {
        eyebrow: 'Implantación industrial',
        title: 'Cómo se diseña una visión 360° que aguante en entorno severo',
        description: 'En maquinaria pesada e industria, la instalación debe resolver vibración, suciedad, agua a presión, geometrías irregulares y riesgos persona-máquina. El sistema solo aporta valor si esa implantación está pensada para el entorno real.',
        steps: [
          'Estudio de maquinaria, ángulos muertos y maniobras críticas del entorno.',
          'Diseño de arquitectura con cámaras, cableado y fijaciones industriales.',
          'Instalación y calibración sobre parque existente o maquinaria nueva.',
          'Validación en obra, patio o nave antes del despliegue operativo a escala.',
        ],
      },
      features: {
        eyebrow: 'Capas del sistema',
        title: 'Beneficios para seguridad y control de maniobra',
        cards: [
          { icon: Eye, title: 'Reduce puntos ciegos en maniobras industriales', desc: 'Fusión en tiempo real de 4-6 cámaras para mostrar todo el entorno del vehículo en una sola vista continua.', tone: 'border-amber-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(255,251,235,0.96))]', iconTone: 'bg-gradient-to-br from-amber-400 to-orange-500', tag: 'Visión 360°' },
          { icon: Shield, title: 'Protege a personas en zona de riesgo', desc: 'Reconocimiento inteligente de trabajadores con alertas escalonadas según proximidad y trayectoria alrededor de la máquina.', tone: 'border-sky-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(239,246,255,0.96))]', iconTone: 'bg-gradient-to-br from-sky-500 to-blue-600', tag: 'Protección activa' },
          { icon: Cpu, title: 'Mantiene fiabilidad en entorno severo', desc: 'Cámaras, cableado y conectores diseñados para polvo, agua a presión y vibraciones severas en obra e industria pesada.', tone: 'border-violet-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(245,243,255,0.96))]', iconTone: 'bg-gradient-to-br from-violet-500 to-fuchsia-500', tag: 'Robustez' },
          { icon: RotateCcw, title: 'Activa alertas en zonas de exclusión', desc: 'Define perímetros virtuales alrededor del vehículo para avisar automáticamente cuando alguien entra en una zona crítica.', tone: 'border-emerald-200/70 bg-[linear-gradient(180deg,rgba(255,255,255,0.98),rgba(236,253,245,0.96))]', iconTone: 'bg-gradient-to-br from-emerald-500 to-teal-500', tag: 'Control de maniobra' },
        ],
      },
      detailSection: {
        eyebrow: 'Maquinaria compatible',
        title: 'Configuración adaptable a parque industrial y vehículos especiales',
        description: 'Arquitectura válida para obra, logística interna, patios industriales y operación municipal con geometrías muy distintas.',
        variant: 'checklist',
        items: ['Excavadoras y retroexcavadoras', 'Palas cargadoras y dumpers', 'Carretillas elevadoras y grúas móviles', 'Vehículos municipales y maquinaria portuaria'],
        bulletColorClass: 'text-emerald-500',
      },
      metrics: { eyebrow: 'Especificaciones clave', title: 'Indicadores de la visión 360° industrial', items: [{ value: 'IP69K', label: 'protección máxima' }, { value: '-30/+70°C', label: 'rango de temperatura' }, { value: '<1 min', label: 'calibración automática' }, { value: 'ISO 5006', label: 'visibilidad industrial' }] },
      faq: {
        eyebrow: 'FAQ para industria',
        title: 'Preguntas frecuentes sobre visión 360° en maquinaria',
        items: [
          { question: '¿Qué maquinaria y vehículos industriales pueden equipar el sistema?', answer: 'Excavadoras, palas, carretillas, grúas móviles, dumpers, vehículos municipales y otra maquinaria pesada con instalación 12V o 24V.' },
          { question: '¿Resiste las condiciones reales de obra?', answer: 'Sí. Está diseñado para polvo, agua a presión, vibraciones y temperaturas extremas con componentes industriales certificados.' },
          { question: '¿Ayuda a reforzar prevención de riesgos?', answer: 'Sí. Mejora visibilidad, control de maniobra y protección colectiva en entornos con interacción persona-máquina.' },
          { question: '¿Cómo se valida la solución en entorno severo antes del despliegue?', answer: 'La instalación se prueba en obra, patio o nave para comprobar cobertura, robustez y utilidad real en maniobra antes de extenderla al resto del parque.' },
        ],
      },
      cta: {
        eyebrow: 'Siguiente paso',
        title: 'Refuerza la seguridad de tu parque industrial con visión 360°',
        description: 'Solicita un estudio técnico para definir cámaras, montaje y configuración de maniobra según tu maquinaria y entorno de trabajo.',
        primaryCtaLabel: 'Ver si encaja en mi flota',
        relatedLinks: [sharedRelatedLinks.camiones, sharedRelatedLinks.construccion, sharedRelatedLinks.portuaria, sharedRelatedLinks.camaras, sharedRelatedLinks.fcw],
      },
    },
  },
};